apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.requestedVolumeClaimSize }}