kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}-worker"
  labels:
    app: "{{ .Release.Name }}-worker"
spec:
  replicas: {{ .Values.cdash.worker.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker"
    spec:
      serviceAccountName: {{ .Values.cdash.serviceAccountName | quote }}
      containers:
        - name: "{{ .Release.Name }}-worker"
          image: {{ .Values.cdash.image | quote }}
          resources:
            {{ toYaml .Values.cdash.worker.resources | nindent 12 }}
          command: [ "/bin/bash", "/cdash/docker/docker-entrypoint.sh" ]
          args: [ "start-worker" ]
          env:
        {{ template "cdash.environment" . }}
