services:
  cdash:
    ports:
      - 443:443
    volumes:
      - type: volume
        source: ${SSL_CERTIFICATE_FILE}
        target: /etc/ssl/certs/mycert.crt
      - type: volume
        source: ${SSL_CERTIFICATE_KEY_FILE}
        target: /etc/ssl/private/mycert.key
