services:
  cdash:
    env_file:
      - ../.env
    ports:
      - 443:443
    volumes:
      - "${SSL_CERTIFICATE_FILE}:/var/www/my-cert.pem"
      - "${SSL_CERTIFICATE_KEY_FILE}:/var/www/my-cert.key"
  worker:
    image: kitware/cdash-worker
    container_name: cdash_worker
    build:
      context: ..
      target: cdash-worker
    environment:
      DB_HOST: database
    deploy:
      replicas: 1
    depends_on:
      cdash:
        condition: service_healthy
    volumes:
      - type: volume
        source: storage
        target: /cdash/storage

volumes:
  storage:
