services:
  cdash:
    env_file:
      - ../.env
    ports:
      - 443:80
    volumes:
      - "${SSL_CERTIFICATE_FILE}:/var/www/cdash.pem"
      - "${SSL_CERTIFICATE_KEY_FILE}:/var/www/cdash.key"
  worker:
    env_file:
      - ../.env
    image: kitware/cdash-worker
    build:
      context: ..
      target: cdash-worker
      # Set the environment variable BASE_IMAGE=ubi to use RedHat UBI as base image
      args:
        BASE_IMAGE: ${BASE_IMAGE-debian}
    environment:
      DB_HOST: database
    deploy:
      replicas: ${NUM_WORKERS:-1}
      restart_policy:
        condition: any
    depends_on:
      cdash:
        condition: service_healthy
    volumes:
      - type: volume
        source: storage
        target: /cdash/storage

volumes:
  storage:
