version: '3.3'
services:
  cdash:
    image: "kitware/cdash"
    container_name: cdash
    build:
      context: .
      dockerfile: ./docker/cdash.docker
      args:
        - CDASH_DB_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
     - "8080:80"
    volumes:
      - type: volume
        source: storage
        target: /home/kitware/cdash/storage
    environment:
      QUEUE_CONNECTION: database
      REMOTE_WORKERS: 1
      CDASH_ROOT_ADMIN_PASS: secret
      CDASH_STATIC_USERS: |
        USER jdoe@acme.com jdoe_secret
          John Doe "ACME Inc."

        ADMIN admin@example.org admin_secret
          Admin User "Example Foundation"

        donotreply@example.org oldsecret newsecret

        strange.name@gmail.com strange_secret
        INFO Str@nge N@me "Str@nge Rese@rch Gr0up LLC."

        DELETE remove.this.user@example.org delete_secret

  worker:
    image: "kitware/cdash-worker"
    environment:
      CDASH_ROOT_ADMIN_PASS: secret
      CDASH_REMOTE_PROCESSOR: 1
      QUEUE_CONNECTION: database
    build:
      context: .
      dockerfile: ./docker/cdash-worker.docker
      args:
        - CDASH_DB_HOST=mysql
    deploy:
      replicas: 1
    depends_on:
      - mysql
      - cdash
    volumes:
      - type: volume
        source: storage
        target: /home/kitware/cdash/storage

  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'cdash'
      MYSQL_ROOT_HOST: '%'
volumes:
  storage: