kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-website"
data:
  FILESYSTEM_DRIVER: "s3"
  LOG_CHANNEL: "stderr"
  QUEUE_CONNECTION: "database"
  {{ if .Values.minio.enabled }}
  AWS_URL: "http://{{ .Release.Name }}-minio:9000/{{ .Release.Name }}/"
  AWS_ENDPOINT: "http://{{ .Release.Name }}-minio:9000"
  AWS_USE_PATH_STYLE_ENDPOINT: "true"
  {{ end }}
  {{- .Values.cdash.env | nindent 2 }}
