{{- $appSecretName := printf "%s-%s" .Release.Name "website" -}}

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ $appSecretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # Generate a random APP_KEY if one doesn't already exist
  {{- $oldAppSecret := lookup "v1" "Secret" .Release.Namespace $appSecretName }}
  {{- $oldAppSecretData := (get $oldAppSecret "data") | default dict }}
  APP_KEY: {{ (get $oldAppSecretData "APP_KEY") | default (randAlphaNum 32 | b64enc) | quote }}
  AWS_ACCESS_KEY_ID: {{ "admin" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ (get $oldAppSecretData "AWS_SECRET_ACCESS_KEY") | default (randAlphaNum 32 | b64enc) | quote }}
  DB_PASSWORD: {{ (get $oldAppSecretData "DB_PASSWORD") | default (randAlphaNum 32 | b64enc) | quote }}
