/**
 * TODO: Make this test independent of the other tests.
 */
describe('All projects page', () => {
  it('switches between active and all projects', () => {
    cy.visit('/projects');
    cy.get('[data-cy="all-projects"]').should('not.contain', 'never');
    cy.contains('Show All Projects').click();
    cy.get('[data-cy="all-projects"]').should('contain', 'never');
    cy.contains('Show Active Projects').click();
    cy.get('[data-cy="all-projects"]').should('not.contain', 'never');
  });

  it('shows private projects when logged in', () => {
    cy.visit('/projects/all');
    // ProjectTest4Db is a random private project generated by previous tests
    cy.get('[data-cy="all-projects"]').should('not.contain', 'ProjectTest4Db');
    cy.login();
    cy.visit('/projects/all');
    cy.get('[data-cy="all-projects"]').should('contain', 'ProjectTest4Db');
  });
});
